# Generated by Django 5.2.1 on 2025-06-03 10:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Kurs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=100)),
                ('opis', models.TextField()),
                ('typ', models.CharField(choices=[('O', 'Online'), ('S', 'Stacjonarny')], max_length=1)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kursy', to='kursy.autor')),
            ],
        ),
        migrations.CreateModel(
            name='Lekcja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tytul', models.CharField(max_length=100)),
                ('autorzy', models.ManyToManyField(related_name='lekcje', to='kursy.autor')),
                ('kurs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lekcje', to='kursy.kurs')),
            ],
        ),
    ]
